`define OP_LW 35
`define OP_SW 43
`define OP_BEQ 4
`define OP_R 0
`define OP_J 2
`define OP_ADDI 8
`define OP_ANDI 12
`define OP_ORI 13
`define OP_LUI 15
`define OP_BNE 5
`define OP_SLTI 10
`define OP_JAL 3
`define FUNC_ADD 32
`define FUNC_OR  37
`define FUNC_NOR 39
`define FUNC_AND 36
`define FUNC_SLT 42
`define FUNC_SUB 34
`define FUNC_SRL 2
`define FUNC_JR 8
`define FUNC_JALR 9 