`define ROP 0
`define ADDIOP 8
`define ADDIUOP 9
`define ANDIOP 12
`define ORIOP 13
`define XORIOP 14
`define LUIOP 15
`define SLTIOP 10
`define SLTIUOP 11
`define BEQOP 4
`define BGEZOP 1
`define BGTZOP 7
`define BLEZOP 6
`define BLTZOP 1
`define BNEOP 5
`define JOP 2
`define JALOP 3
`define LBOP 32
`define LBUOP 36
`define LHOP 33
`define LHUOP 37
`define LWOP 35
`define SBOP 40
`define SHOP 41
`define SWOP 43
`define ADDFUNCT 32
`define ADDUFUNCT 33
`define ANDFUNCT 36
`define NORFUNCT 39
`define ORFUNCT 37
`define XORFUNCT 38
`define SLLFUNCT 0
`define SLLVFUNCT 4
`define SRAFUNCT 3
`define SRAVFUNCT 7
`define SRLFUNCT 2
`define SRLVFUNCT 6
`define SUBFUNCT 34
`define SUBUFUNCT 35
`define SLTFUNCT 42
`define SLTUFUNCT 43
`define JALRFUNCT 9
`define JRFUNCT 8

   